module.exports = {
	BRAND: 'MAKKI',
	DEFAULT_ACCOUNT_NAME: 'Account',
	ROUTES: {
		UNSIGNED_LOGIN:             'UNSIGNED_LOGIN',
		UNSIGNED_REGISTER:          'UNSIGNED_REGISTER',
		UNSIGNED_REGISTER_MNEMONIC: 'UNSIGNED_REGISTER_MNEMONIC',
		UNSIGNED_RECOVERY:          'UNSIGNED_RECOVERY',
		UNSIGNED_RECOVERY_PASSWORD: 'UNSIGNED_RECOVERY_PASSWORD',
		UNSIGNED_RECOVERY_SCAN:     'UNSIGNED_RECOVERY_SCAN',

		SIGNED_VAULT:               'SIGNED_VAULT',
		SIGNED_VAULT_ACCOUNT:       'SIGNED_VAULT_ACCOUNT',

	} 
}